// 컨텐츠 불러오기
export const GET_VOTES_FAILURE = "GET_VOTES_FAILURE";
export const GET_VOTES_SUCCESS = "GET_VOTES_SUCCESS";
export const GET_VOTES_REQUEST = "GET_VOTES_REQUEST";

// 컨텐츠 저장
export const SET_VOTES_FAILURE = "SET_VOTES_FAILURE";
export const SET_VOTES_SUCCESS = "SET_VOTES_SUCCESS";
export const SET_VOTES = "SET_VOTES";

// 댓글
export const REGISTER_COMMENT = "REGISTER_COMMENT";
export const REGISTER_COMMENT_SUCCESS = "REGISTER_COMMENT_SUCCESS";
export const REGISTER_COMMENT_FAILURE = "REGISTER_COMMENT_FAILURE";

// 댓글 삭제
export const DELETE_COMMENT = "DELETE_COMMENT";
