// 컨텐츠 불러오기
export const GET_VOTES_FAILURE = "GET_VOTES_FAILURE";
export const GET_VOTES_SUCCESS = "GET_VOTES_SUCCESS";
export const GET_VOTES_REQUEST = "GET_VOTES_REQUEST";

// 컨텐츠 저장 및 투표한 컨텐츠 불러오기
export const GET_VOTED_FAILURE = "GET_VOTED_FAILURE";
export const GET_VOTED_SUCCESS = "GET_VOTED_SUCCESS";
export const GET_VOTED_REQUEST = "GET_VOTED_REQUEST";
// 댓글
export const REGISTER_COMMENT = "REGISTER_COMMENT";
export const REGISTER_COMMENT_SUCCESS = "REGISTER_COMMENT_SUCCESS";
export const REGISTER_COMMENT_FAILURE = "REGISTER_COMMENT_FAILURE";
// 댓글 받아오기
export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE";
// 투표했는지 확인
export const GET_FIRST_FAILURE = "GET_FIRST_FAILURE";
export const GET_FIRST_SUCCESS = "GET_FIRST_SUCCESS";
export const GET_FIRST_REQUEST = "GET_FIRST_REQUEST";
// 댓글 삭제
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";