// 컨텐츠 불러오기
export const GET_MAIN_FAILURE = "GET_MAIN_FAILURE";
export const GET_MAIN_SUCCESS = "GET_MAIN_SUCCESS";
export const GET_MAIN = "GET_MAIN";

// 좋아요 확인하기
export const GET_LIKE_FAILURE = "GET_LIKE_FAILURE";
export const GET_LIKE_SUCCESS = "GET_LIKE_SUCCESS";
export const GET_LIKE = "GET_LIKE";

// Like BT 눌렀을 때
export const PUSH_LIKE_BT_FAILURE = "PUSH_LIKE_BT_FAILURE";
export const PUSH_LIKE_BT_SUCCESS = "PUSH_LIKE_BT_SUCCESS";
export const PUSH_LIKE_BT = "PUSH_LIKE_BT";

// Like 취소하기
export const PUSH_DISLIKE_BT_FAILURE = "PUSH_DISLIKE_BT_FAILURE";
export const PUSH_DISLIKE_BT_SUCCESS = "PUSH_DISLIKE_BT_SUCCESS";
export const PUSH_DISLIKE_BT = "PUSH_DISLIKE_BT";

// 써치
export const GET_MAIN_SEARCH_FAILURE = "GET_MAIN_SEARCH_FAILURE";
export const GET_MAIN_SEARCH_SUCCESS = "GET_MAIN_SEARCH_SUCCESS";
export const GET_MAIN_SEARCH_REQUEST = "GET_MAIN_SEARCH_REQUEST";